### ISSUE TITLE
Autoprefixer blocks every other feature

### ISSUE THREAD

**Issue by designorant** [danielhusar/grunt-pleeease#9]
I'm not sure whether it's related to #6 (likely not as I've tested it with the config provided in the [README](https://github.com/danielhusar/grunt-pleeease/blob/master/README.md#the-pleeease-task)) or whether it was a bug in the `pleeease` used in `grunt-pleeease` but for some reason `autoprefixer` blocks the other `pleeease` goodies.

##### gruntfile.js
````js
pleeease: {
    options: {
        autoprefixer: {
            'browsers': ['> 1%', 'Explorer >= 8'],
            'map': true
        },
        opacity: true,
        pseudoElements: true
    },
    dist: {
        files: [{
            expand: true,
            cwd: '<%= config.tmp %>/styles/',
            src: '{,*/}*.css',
            dest: '<%= config.tmp %>/styles/'
        }]
    }
}
````

##### style.scss
````scss
a::before {
    opacity: 0.5;
    transition: all .15s ease-out;
}
````

##### Result:
````scss
a::before {
    opacity: 0.5;
    -webkit-transition: all .15s ease-out;
            transition: all .15s ease-out;
}
````

##### Expected result:
````css
a:before {
    opacity: 0.5;
    filter: alpha(opacity=50);
    -webkit-transition: all .15s ease-out;
            transition: all .15s ease-out;
}
````

##### Result without `autoprefixer`
````css
a:before {
    opacity: 0.5;
    filter: alpha(opacity=50);
    transition: all .15s ease-out;
}
````
